project:
  type: default
  output-dir: _output
  render:
    - index.qmd
    - downloads/*.qmd

format:
  html:
    theme: none
    minimal: true
    self-contained: true
    toc: false
    css: ../shared/brand.css
